In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('C:/Users/manue/Documents/Programming/Python/DABA/프로젝트/전처리/제품이름_전처리_이름.csv')
df.head()

                          Unnamed: 0  GOODS_NM goods_kor
0                  일회용주사기(D/Syringe)       173    일회용주사기
1                 일회용주사침 (D/Needles)       123   일회용주사침
2  포리카테타 (FOLEY CATHETER) - SILICONE        61  포리카테타
3                    접은거즈(FoldGauze)        58      접은거즈
4               일회용주사기(D/Syringe)-카톤        51  일회용주사기카톤

In [8]:
df.iloc[20521]

Unnamed: 0    로우텍정(병)
GOODS_NM            1
goods_kor         로우텍
Name: 20521, dtype: object

# 전치리 함수 정의

In [34]:
import re

def pre_processing(goods_nm):
#     if goods_nm.str.contains('크림|정|서방정|액|캡슐|로션|필름|시럽|겔', na = False):
#         return print(goods_nm)
    
    #matches = ['크림','정','서방정','액','캡슐','로션','필름','시럽','겔']
    matches = ['국제멸균','일동','대웅','디앤비','광동','뽀로로','웰팜스','일성','재스퍼','뉴바이오','한일','수성','닥터그린','보령',
              '훼미리','제일','덴탈마스터']
        
#    matches = ['한신','현재','삼성','닥터헬퍼','유한','카톤','한미','영풍','하나케어','닥터스판','코지','맥손','근화','뉴케어','서머스킨',
#               '국제','닥터체크','점안','제이팜','오투웰','테이핑','덴탈프로','녹십자','대성','신풍','경남제약','대일','셀트리온','부광',
#               '상아','명인','신신','한국콜마','두원','수암제약','세트','대일밴드','유한킴벌리']

#    matches = ['종근당','동광','홈세이프','중외','피엠에스','서울','코반','헬스퓨어','경남제약','케이엠에스','시에스베리아',
#              '유엔아이','경남','뽀롱뽀롱','겨울왕국','네오프렌','바이오파마','루크','대한','기획','크리넥스','성광','홈닥터',
#              '오므론','크림','정','서방정','액','캡슐','로션','필름','시럽','겔']

#    matches = ['젤','캅셀','주','과립','약품','제약','씨알','펜믹스','한올','동화','일양','일양바이오','신일','삼천당','실버포우먼','영진',
#               '동성','바이넥스','신일','경보','명인','제이에스','명문','유영','명인','우리들','에이프로','크라운','점안','서방','연질','수화물','세미','복합']
    
    if any(x in goods_nm for x in matches):
        return re.sub(r'|'.join(map(re.escape, matches)), '', goods_nm)

# 전처리 원하는 부분 확인

In [35]:
# temp_df = df[['goods_kor']].iloc[20521:33601]
temp_df

               goods_kor
20521                로우텍
20522         안심손소독 스프레이
20523        파마라스틱 포돌로지
20524             콜대원키즈펜
20525     듀라셀 알카라인 건전지
...                  ...
33596               비바드론
33597         오징어먹물 코팅칼라
33598       시크릿쥬쥬 멀티비타민리
33599               알로시아
33600  강철소방대 파이어로보 열냉각시트

[13080 rows x 1 columns]

# 전치러 함수 실행

In [36]:
for idx, row in temp_df.iterrows():
    #print(row.goods_kor)
    #print(idx)
    #matches = ['크림','정','서방정','액','캡슐','로션','필름','시럽','겔']
    matches = ['국제멸균','일동','대웅','디앤비','광동','뽀로로','웰팜스','일성','재스퍼','뉴바이오','한일','수성','닥터그린','보령','보령바이오',
              '훼미리','제일','덴탈마스터']
        
#    matches = ['한신','현재','삼성','닥터헬퍼','유한','카톤','한미','영풍','하나케어','닥터스판','코지','맥손','근화','뉴케어','서머스킨',
#               '국제','닥터체크','점안','제이팜','오투웰','테이핑','덴탈프로','녹십자','대성','신풍','경남제약','대일','셀트리온','부광',
#               '상아','명인','신신','한국콜마','두원','수암제약','세트','대일밴드','유한킴벌리']

#    matches = ['종근당','동광','홈세이프','중외','피엠에스','서울','코반','헬스퓨어','경남제약','케이엠에스','시에스베리아',
#              '유엔아이','경남','뽀롱뽀롱','겨울왕국','네오프렌','바이오파마','루크','대한','기획','크리넥스','성광','홈닥터',
#              '오므론']
    
#    matches = ['젤','캅셀','주','과립','약품','제약','씨알','펜믹스','한올','동화','일양','일양바이오','신일','삼천당','실버포우먼','영진',
#               '동성','바이넥스','신일','경보','명인','제이에스','명문','유영','명인','우리들','에이프로','크라운','점안','서방','연질','수화물','세미','복합']
              
    if type(temp_df.loc[idx]['goods_kor']) == float:
        pass
    elif any(x in temp_df.loc[idx]['goods_kor'] for x in matches):
        temp_df.loc[idx] = pre_processing(temp_df.loc[idx]['goods_kor'])
    #print(temp_df.loc[idx]['goods_kor'])

In [37]:
temp_df

               goods_kor
20521                로우텍
20522         안심손소독 스프레이
20523        파마라스틱 포돌로지
20524             콜대원키즈펜
20525     듀라셀 알카라인 건전지
...                  ...
33596               비바드론
33597         오징어먹물 코팅칼라
33598       시크릿쥬쥬 멀티비타민리
33599               알로시아
33600  강철소방대 파이어로보 열냉각시트

[13080 rows x 1 columns]

In [39]:
edited_df = df[['goods_kor']].iloc[17102:20521]
edited_df

                   goods_kor
17102                   레티라진
17103              고압증기 멸균기
17104               미카르디스플러스
17105               인체모형 대장
17106                 포스넬플러스
...                      ...
20516              팔팔포맨 쏘팔메토
20517              만능롤러 마사지기
20518               플러스디알레드론
20519              누기플러스 패드
20520  어헤즈 프리미엄 히든 테라피 트리트먼트

[3419 rows x 1 columns]

In [40]:
result_df = pd.concat([edited_df,temp_df])
result_df

               goods_kor
17102               레티라진
17103          고압증기 멸균기
17104           미카르디스플러스
17105           인체모형 대장
17106             포스넬플러스
...                  ...
33596               비바드론
33597         오징어먹물 코팅칼라
33598       시크릿쥬쥬 멀티비타민리
33599               알로시아
33600  강철소방대 파이어로보 열냉각시트

[16499 rows x 1 columns]

# 결과물 저장 및 복사 붙이기

In [42]:
result_df.to_csv('210818_17102-33601.csv', index = False, encoding='utf-8-sig')